"""SFW authored decision graphs. Public views reveal only the current choices."""
def option(label, text, *, stat=None, dc=14, success=None, failure=None, critical_failure=None, requires=None):
    return {'label':label,'description':text,'stat':stat,'difficulty':dc,'success':success or {'finish':'success'},'failure':failure or {'finish':'failure'},'critical_failure':critical_failure or failure or {'finish':'failure'},'requires':requires}

SCENES = {
    'goblin_smoke_signals': {'start':'signals','nodes':{
        'signals':{'title':'Smoke at the crossroads','text':'Three short plumes rise from the hedgerow. A goblin runner checks the road, then disappears behind a screen of branches. The party has time to follow the runner or examine the abandoned signal fire.',
          'choices':{
            'follow':option('Follow the runner','Survival check. A failed pursuit brings the scouts into a fight; a disastrous pursuit draws their commander.',stat='survival',dc=15,success={'next':'chart','text':'The party keeps out of sight and finds a chart pinned beneath the signal shelter.'},failure={'battle':'goblin_smoke_signals','text':'A snapped branch gives the party away. The signal crew blocks the road.'},critical_failure={'battle':'contract:goblin_chieftain','boss':True,'text':'The runner was bait. A warhost commander arrives with a trained escort.'}),
            'embers':option('Read the signal fire','INT check. Failure destroys an optional clue, but the investigation continues.',stat='int',dc=14,success={'next':'chart','bonus':'signal_lens','text':'Beneath the ash, the party finds a lens etched with the destinations of the signal.'},failure={'next':'chart','text':'The wet ash collapses over the markings. The lens is ruined, but footprints still lead to the chart shelter.'},critical_failure={'battle':'goblin_smoke_signals','text':'The shelter is watched. The scouts catch the party kneeling beside the fire.'}),
          }},
        'chart':{'title':'The farm chart','text':'The chart marks two inhabited farms and an old road into Lareth. Taking it would give the guild a warning. Following the road might reveal who gives the orders.',
          'choices':{
            'return':option('Take the warning home','Secure the investigation without another roll.',success={'finish':'success','text':'The party folds the chart and returns before the signal crew can recover it.'}),
            'trail':option('Trace the command route','Survival check. Success improves the reward; failure still delivers the warning. A critical failure starts a fight.',stat='survival',dc=16,success={'finish':'success','bonus':'signal_lens','text':'The tracks connect the signal post to a staffed supply route. The guild now knows where to intercept the next message.'},failure={'finish':'success','text':'Fresh wagon tracks bury the trail. The party returns with the farm warning, but no command route.'},critical_failure={'battle':'goblin_smoke_signals','text':'Scouts circle back while the party studies the tracks. The warning must now be carried out through a fight.'})}}}},
    'black_banner_ledger': {'start':'case','nodes':{
        'case':{'title':'The courier’s locked case','text':'A recovered courier case contains tribute records written in two different hands. A wax seal connects the payments to an abandoned royal storehouse. Opening the seal carelessly could destroy the names inside.',
          'choices':{
            'decode':option('Work through the cipher','INT check. Failure costs a bonus cipher reward; the storehouse lead remains.',stat='int',dc=15,success={'next':'witness','bonus':'ledger_ring','text':'The second hand records routes, not debts. One entry names the next tribute convoy.'},failure={'next':'witness','text':'The cipher remains incomplete. The party can still follow the storehouse seal.'},critical_failure={'battle':'contract:highway_ambush','boss':True,'text':'A hidden signal slips out of the case. The Banner’s retrieval officer comes to reclaim it.'}),
            'witness':option('Take the seal to a former clerk','Find someone who knows the mark. No roll is needed to seek an audience.',success={'next':'witness','text':'A former toll clerk recognizes the seal and agrees to speak away from the road.'}),
            'force':option('Open the hidden compartment','DEX check. An intact cipher has a better exclusive-drop chance. Failure destroys the records and fails the contract; critical failure alerts the retrieval officer.',stat='dex',dc=16,success={'finish':'success','bonus':'ledger_ring_intact','text':'The hidden compartment opens with its records intact. The complete convoy cipher can be delivered directly to the guild.'},failure={'finish':'failure','text':'The catch tears through the records. Ink and wax seal the scraps together; the guild cannot reconstruct the tribute route.'},critical_failure={'battle':'contract:highway_ambush','boss':True,'text':'A tripwire releases a signal flare from the case. The Banner’s retrieval officer catches the party on the road.'})}},
        'witness':{'title':'A clerk who has already paid','text':'The clerk says the Banner has taken payment twice and threatens to take a third. They will identify the convoy route if the guild offers a credible way out.',
          'choices':{
            'plan':option('Explain how the guild will protect the route','INT check. Failure ends the interview without losing the contract’s basic evidence.',stat='int',dc=15,success={'finish':'success','bonus':'ledger_ring','text':'The clerk names the departure road and hands over the toll captain’s signet. The next tribute shipment can be intercepted.'},failure={'finish':'success','text':'The clerk refuses to risk their family. The guild keeps the ledger, but must find the convoy route another way.'},critical_failure={'battle':'contract:highway_ambush','text':'Someone at the tollhouse overhears the interview. Armed collectors close the road.'}),
            'leave':option('Do not put the clerk at risk','Return with the ledger. No extra reward check.',success={'finish':'success','text':'The party leaves the clerk out of the report and carries the ledger back to the guild.'})}}}},
    'bell_beneath_mud': {'start':'bell','nodes':{
        'bell':{'title':'A bell with no tower','text':'Each time the buried bell sounds, footsteps gather beyond the flooded chapel. A brass clapper is visible through a crack in the mud. The bell must be silenced before the next procession reaches the road.',
          'choices':{
            'ward':option('Break the binding rite','Magic check. Failure wakes the chapel guard; a critical failure wakes its oathkeeper.',stat='magic',dc=16,success={'next':'recover','text':'The final name fades from the bell’s rim. The footsteps stop.'},failure={'battle':'contract:undead_bone_collectors','text':'The rite breaks unevenly. The chapel’s dead gather between the party and the exit.'},critical_failure={'battle':'contract:undead_death_knight','boss':True,'text':'The bell answers with a second note. Its oathkeeper rises from beneath the chapel stones.'}),
            'lift':option('Lever the clapper free','Building check. A failed attempt ruins an optional relic but can still silence the bell.',stat='building',dc=15,success={'next':'recover','bonus':'chapel_thread','text':'The clapper lifts cleanly from its socket. The party preserves the binding thread wrapped around it.'},failure={'finish':'success','text':'The clapper snaps as the party levers it free. The bell falls silent, but the old thread cannot be recovered.'},critical_failure={'battle':'contract:bone_patrol','text':'The lever shifts a buried tombstone. The chapel patrol climbs from the floodwater.'})}},
        'recover':{'title':'Names in the floodwater','text':'A small reliquary lies beside the silent bell. Its chain is tangled around a drowned stone figure. The road is safe for now; recovering the reliquary is optional.',
          'choices':{
            'relic':option('Recover the reliquary','Medicine check. Failure loses the optional reward and the contract still succeeds.',stat='medicine',dc=15,success={'finish':'success','bonus':'chapel_thread','text':'The party frees the chain without disturbing the remains and carries the reliquary out of the chapel.'},failure={'finish':'success','text':'The reliquary slips into the flooded vault. The bell is silent, and the party leaves it there.'},critical_failure={'battle':'contract:bone_patrol','text':'The stone figure moves as the chain is pulled. The party must hold off the chapel guard.'}),
            'leave':option('Leave the dead undisturbed','Complete the contract without risking the optional relic.',success={'finish':'success','text':'The party marks the silent chapel for the guild and returns to the road.'})}}}},
}

APPROACH = {'start':'approach','nodes':{'approach':{'title':'Choose the approach','text':'The enemy holds the far approach. The party can force a direct engagement, scout a better opening, or use its tools to prepare a defensive lane.', 'choices':{
    'direct':option('Attack head on','Start the encounter with the normal deployment. No preparation roll.',success={'battle':'default','text':'The party advances openly and meets the defenders on the approach.'}),
    'scout':option('Scout an ambush position','Survival check. Success finds the enemies asleep for three rounds. Attacking any enemy wakes them all, even on a miss. Failure gives the defenders the first move; a critical failure strengthens their commander.',stat='survival',dc=16,success={'battle':'default','setup':'ambush','text':'The scouts find the camp asleep and guide the party into position. The first attack will wake everyone.'},failure={'battle':'default','setup':'alert','text':'The defenders notice the scouts and prepare for the approach.'},critical_failure={'battle':'default','boss':True,'setup':'alert','text':'The scouts stumble into the commander’s reserve position. The party must fight a stronger commander.'}),
    'blockade':option('Build a defensive lane','Building check; needs an Engineer or Constructor training. Success places breakable cover near the party. Failure uses the normal deployment.',stat='building',dc=15,requires='builder',success={'battle':'default','setup':'blockade','text':'The party braces salvaged timbers across the flank, leaving a lane open for a controlled advance.'},failure={'battle':'default','text':'The timber will not hold. The party abandons the work and deploys normally.'},critical_failure={'battle':'default','setup':'alert','text':'The work gives away the approach. The defenders take the first move.'})}}}}

SCENES['hedgerow_terms']={'start':'terms','nodes':{'terms':{'title':'Terms at the ford','text':'The watch keeper spreads a map of the farms across the table. “I can warn your guild about the raids. But I need to know you will answer when the horn sounds. What can you offer?”','choices':{
    'agree':option('Agree to answer the watch horn','Accept the basic agreement and unlock the defense contract. No bonus reward check.',success={'finish':'success','text':'The party agrees to answer the watch horn. The keeper marks Fortcamp on the warning route and sends over the first defense request.'}),
    'plan':option('Offer a shared patrol plan','INT check. A convincing plan has a chance to teach the lead the Guard perk. Failure ends negotiations without an invitation.',stat='int',dc=13,success={'finish':'success','bonus':'watch_contact','text':'The patrol plan leaves the farms covered while giving the guild a clear response route. The keeper agrees to share the watch network’s warnings.'},failure={'finish':'failure','text':'The keeper points to an uncovered farm on the map. The plan leaves too many people exposed, and the talks end without an agreement.'},critical_failure={'finish':'failure','text':'The proposed patrol route crosses the watch’s concealed warning posts. The keeper refuses to disclose more until the guild can offer a workable plan.'}),
    'decline':option('Decline the agreement','End the negotiations. No defense invitation or reward.',success={'finish':'failure','text':'The party cannot promise a response and leaves the watch network to make other arrangements.'})}}}}

def apply_storylines(missions):
    from copy import deepcopy
    for mission_id,definition in SCENES.items():
        missions[mission_id]['decision_scene']=deepcopy(definition)
        missions[mission_id]['resolution_mode']='choices'
        missions[mission_id]['bodyguard_slots']=min(1,4-missions[mission_id]['party_size'])
    for mission in missions.values():
        if mission.get('combat_encounter') and mission['combat_encounter']['id'].startswith(('contract:','goblin_warcamp')):
            mission['decision_scene']=deepcopy(APPROACH)
            mission['resolution_mode']='choices → tactical'
            mission['bodyguard_slots']=max(0,min(1,4-mission['party_size']))
    for mission_id,encounter in {'flooded_underpass':'contract:bone_patrol','restless_graves':'contract:undead_death_knight','goblin_supply_carts':'goblin_warcamp'}.items():
        missions[mission_id]['critical_failure_encounter']={'battle':encounter,'text':'The expedition goes badly wrong. Armed opposition cuts off the return route; the party must fight or escape.'}
        missions[mission_id]['bodyguard_slots']=max(0,min(1,4-missions[mission_id]['party_size']))
