const replies=new Map();
const openCards=new Set();
export function prisonerRecruitmentMarkup(p,esc){
 const r=p.recruitment;if(!r)return '';
 const costs={debt:'gold',rebuild:'wood',wounded:'medicine',heirloom:'Field Pack'};
 const quest=['rival','former','proof','rescue'].includes(r.route)||r.requires_proof&&r.payment_met,secured=p.holding==='prison_cell';
 const attributes=Object.entries(r.candidate?.attributes||{}).map(([a,v])=>`${a.toUpperCase()} ${v}`).join(' · ');
 return `<details class="prison-recruitment" data-prison-talk="${esc(p.id)}" ${openCards.has(p.id)?'open':''}><summary>Conversation & recruitment</summary><div class="prison-recruit-summary"><b>Resistance ${r.resistance}</b><small>${r.requires_terms?'Requires a personal agreement to join.':'Lower resistance to zero, or fulfill their personal terms.'}</small><small>Recruit profile: ${esc(attributes)}</small><small>${esc(r.profile_note)}</small><small>Starting loyalty: ${r.terms_met?'80':r.requires_terms?'80 after their agreement':'70 through negotiation · 80 through an agreement'}</small></div><div class="prison-talk-reply" role="status">${esc(replies.get(p.id)||(r.revealed?r.terms_text:null)||'Speak with the prisoner to learn what they need.')}</div>${r.revealed?`<div class="prison-terms"><b>${r.terms_met?'Agreement fulfilled':quest?'A personal task':`Requested: ${r.cost} ${(r.route==='heirloom'?r.requested_item?.replaceAll('_',' ')||'Field Pack':costs[r.route])}`}</b><small>${r.terms_met?'You can now offer a place in your roster.':quest?'The quest appears on Private Contracts and belongs to this prisoner.':'Payment is consumed once. Equipped items cannot be offered.'}</small></div>`:''}<div class="prisoner-actions"><button data-prisoner-action="talk" data-prisoner-id="${esc(p.id)}">Discuss their terms</button><button data-prisoner-action="negotiate" data-prisoner-id="${esc(p.id)}" ${!secured||r.resistance<=0?'disabled':''}>Warden negotiation</button>${r.revealed&&!r.terms_met?`<button data-prisoner-action="${quest?'quest':'fulfill'}" data-prisoner-id="${esc(p.id)}" ${secured?'':'disabled'}>${quest?'Add / view Private Contract':'Fulfill agreement'}</button>`:''}<button data-prisoner-action="recruit" data-prisoner-id="${esc(p.id)}" ${secured&&(r.terms_met||!r.requires_terms&&r.resistance<=0)?'':'disabled'}>Offer recruitment</button></div><small>Wardens use effective INT. One negotiation per warden every 30 minutes, shared across their prisoners.</small></details>`;
}
export function rememberPrisonReply(id,text){if(text)replies.set(id,text);openCards.add(id)}
export function bindPrisonCards(root){root.querySelectorAll('[data-prison-talk]').forEach(d=>d.ontoggle=()=>{if(d.open)openCards.add(d.dataset.prisonTalk);else openCards.delete(d.dataset.prisonTalk)})}
