let session=null, bindings=null;
export function rogueSession(view){const actor=view.units?.[view.current_unit_id],id=actor?.special?.id,key=`${view.seed}:${actor?.id}:${id}`;if(session?.key!==key)session={key,rotation:0,target:null,landing:null,center:null,attack:'basic'};return session}
export function resetRoguePlacement(){session=null;bindings?.abort()}
export function placementCommand(view,s){const a=view.units?.[view.current_unit_id],id=a?.special?.id,p=view.rogue_previews?.[id];if(!p)return null;
 if(p.kind==='shadowstep'&&p.targets?.[s.target]?.some(c=>c.x===s.landing?.x&&c.y===s.landing?.y))return {action:'skill',skill_id:id,target_id:s.target,...s.landing};
 if(p.kind==='backflip'&&p.landings.some(c=>c.x===s.landing?.x&&c.y===s.landing?.y))return {action:'skill',skill_id:id,...s.landing};
 if(p.kind==='caltrops'&&p.strips[`${s.center?.x},${s.center?.y},${s.rotation}`])return {action:'skill',skill_id:id,...s.center,rotation:s.rotation};
 if(p.kind==='throwing_knife'&&p.attacks[s.attack]?.[s.target])return {action:s.attack==='basic'?'attack':'skill',...(s.attack==='basic'?{}:{skill_id:s.attack}),target_id:s.target,knife_skill_id:id};return null;
}
export function roguePreviewView(view,mode){const id=view.units?.[view.current_unit_id]?.special?.id,p=view.rogue_previews?.[id];if(mode!=='skill'||p?.kind!=='throwing_knife')return view;const s=rogueSession(view);return {...view,attack_previews:Object.fromEntries(Object.entries(p.attacks[s.attack]||{}).map(([id,forecast])=>[id,{skill:forecast}]))}}
export function mountRoguePlacement({view,mode,field,host,send,cancel,escape,blocked=()=>false}){
 bindings?.abort();field?.classList.remove('rogue-placement');host?.querySelector('.rogue-placement-panel')?.remove();field?.querySelector('.rogue-target-layer')?.remove();field?.querySelectorAll('.rogue-target-focus').forEach(el=>el.classList.remove('rogue-target-focus'));const actor=view.units?.[view.current_unit_id],p=view.rogue_previews?.[actor?.special?.id];if(!field||mode!=='skill'||!p)return;
 field.classList.add('rogue-placement');bindings=new AbortController();const opts={signal:bindings.signal};const s=rogueSession(view),layer=document.createElement('div'),panel=document.createElement('section');layer.className='rogue-target-layer';panel.className='rogue-placement-panel';field.append(layer);host.append(panel);
 const paint=()=>{let cells=p.kind==='shadowstep'?p.targets[s.target]||[]:p.kind==='backflip'?p.landings:p.kind==='caltrops'?p.strips[`${s.center?.x},${s.center?.y},${s.rotation}`]||[]:[];const valid=!!placementCommand(view,s);if(p.kind==='caltrops'&&s.center&&!cells.length)cells=[-1,0,1].map(i=>({x:s.center.x+(s.rotation?0:i),y:s.center.y+(s.rotation?i:0)})).filter(c=>c.x>=0&&c.x<view.width&&c.y>=0&&c.y<view.height);layer.innerHTML=cells.map(c=>`<i class="${p.kind==='caltrops'&&!valid?'invalid':s.landing?.x===c.x&&s.landing?.y===c.y?'chosen':''}" style="left:${c.x/view.width*100}%;top:${c.y/view.height*100}%;width:${100/view.width}%;height:${100/view.height}%"></i>`).join('');
 const help={shadowstep:'Choose an enemy, then an adjacent landing.',backflip:'Choose a highlighted cardinal landing.',caltrops:'Choose the centre of a three-tile strip. R rotates.',throwing_knife:'Choose an attack, then a target beyond melee range.'}[p.kind];
 panel.innerHTML=`<div><strong>${escape(actor.special.name)}</strong><small>${help} ${p.kind==='throwing_knife'?'Main attack: ends activation.':'Quick Action: main action remains.'}</small></div>${p.kind==='throwing_knife'?`<div class="rogue-attack-choices">${Object.keys(p.attacks).map(id=>`<button data-rogue-attack="${escape(id)}" aria-pressed="${s.attack===id}">${escape(id==='basic'?'Basic Attack':actor.skills.find(a=>a.id===id)?.name||id)}</button>`).join('')}</div>`:''}${p.kind==='caltrops'?'<button data-rogue-rotate>R ? Rotate</button>':''}<button data-rogue-confirm ${!placementCommand(view,s)?'disabled':''}>Confirm</button><button data-rogue-cancel>C ? Cancel</button>`;
 panel.querySelector('[data-rogue-confirm]').onclick=()=>{if(blocked())return;const command=placementCommand(view,s);if(command){resetRoguePlacement();send(command)}};panel.querySelector('[data-rogue-cancel]').onclick=()=>{resetRoguePlacement();cancel()};const rotate=panel.querySelector('[data-rogue-rotate]');if(rotate)rotate.onclick=()=>{s.rotation=1-s.rotation;paint()};panel.querySelectorAll('[data-rogue-attack]').forEach(b=>b.onclick=()=>{s.attack=b.dataset.rogueAttack;s.target=null;paint()});};
 const point=e=>{const rect=field.getBoundingClientRect();return {x:Math.floor((e.clientX-rect.left)/rect.width*view.width),y:Math.floor((e.clientY-rect.top)/rect.height*view.height)}};
 field.addEventListener('click',e=>{e.stopImmediatePropagation();if(blocked())return;const id=e.target.closest('[data-battle-unit]')?.dataset.battleUnit,cell=e.target.closest('[data-battle-cell]')?.dataset.battleCell,c=cell?Object.fromEntries(cell.split(',').map((v,i)=>[i?'y':'x',Number(v)])):view.units[id]?{x:view.units[id].x,y:view.units[id].y}:point(e);if(p.kind==='shadowstep'){if(p.targets[id]?.length){s.target=id;s.landing=null}else s.landing=c}else if(p.kind==='backflip')s.landing=c;else if(p.kind==='caltrops')s.center=c;else s.target=id||Object.values(view.units).find(u=>u.x===c.x&&u.y===c.y)?.id;paint()}, {...opts,capture:true});
 if(p.kind==='caltrops'){let dragging=false;field.addEventListener('pointerdown',e=>{if(e.button===0&&!blocked()){dragging=true;s.center=point(e);paint()}},opts);document.addEventListener('pointerup',e=>{if(!dragging)return;dragging=false;if(!field.contains(e.target)){s.center=null;paint()}},opts);field.addEventListener('pointermove',e=>{if(!blocked()&&e.buttons!==2){const c=point(e);if(c.x!==s.center?.x||c.y!==s.center?.y){s.center=c;paint()}}},opts)}
 document.addEventListener('keydown',e=>{if(e.target.closest('input,textarea,select,[contenteditable]'))return;if(p.kind==='caltrops'&&e.key.toLowerCase()==='r'){e.preventDefault();e.stopImmediatePropagation();if(!blocked()){s.rotation=1-s.rotation;paint()}}},{...opts,capture:true});paint();
}
