import test from 'node:test';
import assert from 'node:assert/strict';
import {existsSync} from 'node:fs';
import {selectRogueCell,placementCommand,rogueSession,resetRoguePlacement,roguePreviewView} from './rogue-ui.js';
import {impactTimeline,movementDuration} from './combat-impact.js';
import {combatAudioSchedule} from './combat-audio.js';
import {skillIcon} from './ability-icons.js';
import {hotbarMarkup} from './combat-hotbar.js';
import {statusVisual} from './combat-status-presentation.js';
import {tacticalPreviewText,statusDetails} from './combat-status-ui.js';
import {zoneOverlay} from './combat-spaces-ui.js';
function view(kind,preview){const id='job:rogue:'+kind;return {seed:'x',current_unit_id:'a',units:{a:{id:'a',special:{id}}},rogue_previews:{[id]:{kind,...preview}}}}
test('Shadowstep commits chosen legal landing only; cancellation spends nothing',()=>{const v=view('shadowstep',{targets:{e:[{x:2,y:3}]}});assert.equal(placementCommand(v,{target:'e'}),null);assert.equal(placementCommand(v,{target:'e',landing:{x:3,y:3}}),null);assert.deepEqual(placementCommand(v,{target:'e',landing:{x:2,y:3}}),{action:'skill',skill_id:'job:rogue:shadowstep',target_id:'e',x:2,y:3});const s=rogueSession(v);s.target='e';resetRoguePlacement();assert.equal(rogueSession(v).target,null)});
test('Caltrops requires valid orientation; Backflip requires legal cardinal destination',()=>{const v=view('caltrops',{strips:{'2,3,1':[{x:2,y:2},{x:2,y:3},{x:2,y:4}]}});assert.equal(placementCommand(v,{center:{x:2,y:3},rotation:0}),null);assert.equal(placementCommand(v,{center:{x:2,y:3},rotation:1}).rotation,1);assert.equal(placementCommand(view('backflip',{landings:[{x:1,y:3}]}),{landing:{x:2,y:4}}),null)});
test('Throwing Knife chooses equipped delivery without moving actor',()=>{const v=view('throwing_knife',{attacks:{basic:{e:{damage_on_hit:20}},'job:rogue:cheap_shot':{e:{damage_on_hit:40}}}});const s=rogueSession(v);s.attack='job:rogue:cheap_shot';s.target='e';const c=placementCommand(v,s);assert.equal(c.skill_id,s.attack);assert.equal(c.knife_skill_id,'job:rogue:throwing_knife');assert.equal(c.x,undefined);assert.equal(roguePreviewView(v,'skill').attack_previews.e.skill.damage_on_hit,40)});
test('Knife contact, damage and death precede enemy action; teleport stays brief',()=>{const events=[{type:'rogue_knife',attack_packet:1,hit:true,impact_surface:'flesh'},{type:'combat_feedback',attack_packet:1,kind:'physical',amount:20},{type:'death_burst',attack_packet:1},{type:'movement',unit_id:'enemy',points:[{x:0,y:0},{x:1,y:0}]}];const t=impactTimeline(events);assert.equal(t[1].start,280);assert.ok(t[3].start>=t[2].start+t[2].duration);const cues=combatAudioSchedule({},events).cues;assert.equal(cues.find(c=>c.name==='melee_stab_flesh').delay,280);assert.equal(movementDuration({teleport:true}),420)});
test('Rogue mobility uses Rogue sound rather than earthbreaker',()=>{const cues=combatAudioSchedule({},[{type:'movement',rogue_motion:'backflip',leap:true,points:[{x:0,y:0},{x:2,y:0}]}]).cues;assert.equal(cues[0].name,'rogue_backflip');assert.ok(!cues.some(c=>c.name==='earthbreaker_launch'))});
test('Eight generated icons exist; quick/main labels and stack previews are readable',()=>{for(const key of ['cheap_shot','crippling_cut','exploit_weakness','shadowstep','caltrops','backflip','trap_expert','throwing_knife'])assert.ok(existsSync(new URL('../public'+skillIcon({id:'job:rogue:'+key}),import.meta.url)));assert.match(hotbarMarkup({skills:[{id:'job:rogue:crippling_cut',name:'Crippling Cut',quick_action:true,type:'active',source_kind:'character',availability:{available:true}}]},0,null,String),/Quick Action/);assert.equal(statusVisual({id:'bleed',layers:[{},{}],turns:1}).count,2);assert.match(tacticalPreviewText({debuff_stacks:{bleed:3,hobbled:3},exploit_power:400}),/6 debuff stacks/);assert.match(statusDetails({id:'hobbled',layers:[{},{}],turns:2},{}).details.join(' '),/halved once/)});
test('Caltrops ground art contains steel caltrops rather than old magical rings',()=>{const html=zoneOverlay([{id:'c',kind:'caltrops',name:'Caltrops',cells:[{x:1,y:2},{x:2,y:2},{x:3,y:2}]}],String);assert.equal((html.match(/class="caltrop-cluster"/g)||[]).length,3);assert.ok(!html.includes('binding_ring.png'))});

import {selectedSkillCommand} from './combat-targeting.js';
test('Knife Exploit selection survives command preparation',()=>{const c={action:'skill',skill_id:'job:rogue:exploit_weakness',knife_skill_id:'job:rogue:throwing_knife',target_id:'e'};assert.deepEqual(selectedSkillCommand(c,{special:{id:'job:rogue:throwing_knife'}}),c);assert.equal(selectedSkillCommand({action:'skill'},{special:{id:'job:rogue:cheap_shot'}}).skill_id,'job:rogue:cheap_shot')});
test('Selecting a Caltrops strip freezes it until confirm or cancel',()=>{const v=view('caltrops',{strips:{'2,3,0':[{}],'4,3,0':[{}]}}),s=rogueSession(v);selectRogueCell(v,s,{x:2,y:3});assert.equal(s.phase,'confirm');selectRogueCell(v,s,{x:4,y:3});assert.deepEqual(s.center,{x:2,y:3});assert.equal(placementCommand(v,s).x,2);resetRoguePlacement()});
