import {escapeHTML as esc} from './mission-board-ui.js';
import {describeGear} from './equipment-ui.js';
export function tradeMarkup(trade,state,content){
  const visiting=trade.factions.find(f=>f.visiting);
  const offer=o=>{const item=content.items[o.item]||{};return `<article class="trade-offer"><div class="trade-item-title">${item.icon?`<img src="${esc(item.icon)}" alt="">`:''}<b>${esc(item.name||o.item)}</b></div><p>${esc(item.description||'')}</p><div class="trade-item-effects">${describeGear(item,content.standalone_perks||{}).filter(line=>line!==item.description).map(line=>`<small>${esc(line)}</small>`).join('')}</div><small>${o.required_relationship!=null?`Relationship ${o.required_relationship} · `:''}${o.id.startsWith('camp:')?'Camp stock':`${o.stock} available`}</small><button data-offer="${esc(o.id)}" ${o.locked||o.stock<1?'disabled':''}>${o.locked?'Build relationship':`Buy · ${o.price} gold`}</button></article>`};
  return `<button class="trade-close">Close</button><div class="eyebrow">CAMP TRADE · ${state.resources.gold} GOLD</div><h2>Travelers and faction contacts</h2><p>Visits and purchases are saved. Reopening never rerolls stock.</p><section class="trade-rotation"><span class="eyebrow">VISITING FACTION TRADER</span><h3>${esc(visiting?.name||'No trader')}</h3><p>Available until ${esc(new Date(trade.rotation.ends_at*1000).toLocaleString())}. Next: ${esc(trade.rotation.next_name)}.</p><small>Traders rotate every 48 hours. Relationship 20 earns a 5% discount; 45 earns 10%. Your contacts can offer contracts while their trader is away.</small><div class="trade-offers">${(visiting?.offers||[]).map(offer).join('')}</div></section>
  <h3>Faction agreements</h3><div class="faction-contact-grid">${trade.factions.map(f=>`<section class="faction-contact"><h4>${esc(f.name)}</h4><small>Relationship ${f.relationship}/100${f.visiting?' · Trader present':''}</small><progress max="100" value="${f.relationship}"></progress>${f.contracts.map(c=>`<div class="faction-job"><b>${esc(c.name)}</b><small>${c.rank}-Rank · ${c.story_consequence?'Earned story consequence':`Relationship ${c.required_relationship}`}</small><button data-faction-contract="${esc(c.id)}" ${c.completed||c.locked?'disabled':''}>${c.completed?'Agreement fulfilled':c.locked?esc(c.lock_reason||'Build relationship'):'Open private agreement'}</button></div>`).join('')}</section>`).join('')}</div>
  <h3>Camp supplies</h3><p>Basic provisions and treatment supplies remain available between merchant visits.</p><div class="trade-basic-supplies">${trade.supplies.map(s=>`<button data-offer="supplies:${s.resource}">Buy 1 ${s.resource} · ${s.price} gold</button>`).join('')}</div><div class="trade-offers">${trade.camp_items.map(offer).join('')}</div>
  <h3>Independent traveling merchant</h3>${trade.merchant?`<small>Available until ${esc(new Date(trade.merchant.expires_at*1000).toLocaleString())}</small><div class="trade-offers">${trade.merchant.offers.map(offer).join('')}</div>`:'<p>No independent merchant is visiting. Their arrival and rare stock are specific to your camp.</p>'}`;
}
