"""Generate an isolated, enlarged preview using the real wall renderer styles."""
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
DEST=ROOT/'staging-terrain/building-toolset-v2'
DEST.mkdir(parents=True,exist_ok=True)
(DEST/'join-preview.html').write_text('''<!doctype html><html><head><meta charset="utf-8"><title>Wall connection check</title></head><body><div id="controls"><label>Material <select id="material"><option>timber</option><option>fieldstone</option><option>limestone</option><option>iron</option></select></label> <label>Rotation <select id="rotation"><option>0</option><option>90</option><option>180</option><option>270</option></select></label> <label><input id="fix" type="checkbox" checked> Show repaired joins</label></div><div id="diagrams"></div><script type="module" src="./join-preview.js"></script></body></html>''',encoding='utf-8')
(DEST/'join-preview.js').write_text('''import '/frontend/src/styles.css';
import {structuralLayout} from '/frontend/src/building-joins.js';
import geometry from '/frontend/src/building-art-geometry.json';
import {overheadPropStyle} from '/frontend/src/map-prop-art.js';
const style=document.createElement('style');style.textContent=`body{margin:20px;background:#181c18;color:#e5dece}#controls{margin-bottom:16px}#diagrams{display:grid;grid-template-columns:repeat(3,380px);gap:20px}.diagram{width:380px}.battlefield{width:380px;height:380px;aspect-ratio:1;background:#30372c}.battle-cell{background:#353b2d}.wall-connector{filter:none}`;document.head.append(style);
function itemHTML(item,fix,sleeve=false){const layout=fix?structuralLayout(item,geometry):{offset:item.art_offset||[0,0]},offset=layout.offset;return `<div class="${sleeve?'battle-decoration wall-connector':'battle-terrain'} ${layout.hideArt?'assembled-wall':''} multi-cell-asset has-prop-art" style="grid-column:${item.x+1};grid-row:${item.y+1};--asset-width:125%;--asset-height:125%;--asset-offset-x:${offset[0]*100}%;--asset-offset-y:${offset[1]*100}%;--asset-rotation:${item.rotation||0}deg;--asset-clip:${item.art_clip?'inset('+item.art_clip.map(v=>v+'%').join(' ')+')':'none'};${overheadPropStyle(item.sprite)}"></div>`}
window.drawJoins=()=>{const f=document.querySelector('#material').value,g=geometry[f],rotation=Number(document.querySelector('#rotation').value),fix=document.querySelector('#fix').checked,panels=[['Corner wall',[{id:'corner',x:1,y:1,sprite:`structure:${f}_corner`},{id:'top',x:0,y:1,sprite:`structure:${f}_wall`,art_offset:[0,-g.join_offset]},{id:'side',x:1,y:2,sprite:`structure:${f}_wall`,rotation:90,art_offset:[g.join_offset,0]}]],['Perimeter T',[{id:'t',x:1,y:0,sprite:`structure:${f}_edge_junction`,art_offset:g.junction_offset},{id:'divider',x:1,y:1,sprite:`structure:${f}_wall`,rotation:90}]],['Centered T',[{id:'center',x:1,y:1,sprite:`structure:${f}_junction`},{id:'left',x:0,y:1,sprite:`structure:${f}_wall`},{id:'right',x:2,y:1,sprite:`structure:${f}_wall`},{id:'below',x:1,y:2,sprite:`structure:${f}_wall`,rotation:90}]],['Cross',[{id:'cross',x:1,y:1,sprite:`structure:${f}_cross`}]],['Short end',[{id:'end',x:0,y:1,sprite:`structure:${f}_end`},{id:'next',x:1,y:1,sprite:`structure:${f}_wall`}]],['Broken corner',[{id:'broken',x:1,y:1,sprite:`structure:${f}_corner_broken`},{id:'previous',x:0,y:1,sprite:`structure:${f}_wall`,art_offset:[0,-g.join_offset]},{id:'below',x:1,y:2,sprite:`structure:${f}_wall`,rotation:90,art_offset:[g.join_offset,0]}]]];for(const [,items] of panels)for(const i of items){for(let n=0;n<rotation/90;n++){[i.x,i.y]=[2-i.y,i.x];if(i.art_offset)i.art_offset=[-i.art_offset[1],i.art_offset[0]]}i.rotation=((i.rotation||0)+rotation)%360}document.querySelector('#diagrams').innerHTML=panels.map(([name,items])=>`<section class="diagram"><h2>${name}</h2><div class="battlefield terrain-style-custom-painted" style="--battle-w:3;--battle-h:3">${Array.from({length:9},(_,i)=>`<div class="battle-cell" style="grid-column:${i%3+1};grid-row:${Math.floor(i/3)+1}"></div>`).join('')}${fix?items.flatMap(i=>structuralLayout(i,geometry).connectors).map(i=>itemHTML(i,fix,true)).join(''):''}${items.map(i=>itemHTML(i,fix)).join('')}</div></section>`).join('')};
document.querySelector('#material').onchange=window.drawJoins;document.querySelector('#fix').onchange=window.drawJoins;document.querySelector('#rotation').onchange=window.drawJoins;window.drawJoins();window.joinPreviewReady=true;
''',encoding='utf-8')
print(DEST/'join-preview.html')
