import {writeFileSync} from 'node:fs';
const tabs=await(await fetch('http://127.0.0.1:9229/json')).json(),ws=new WebSocket(tabs.find(t=>t.type==='page').webSocketDebuggerUrl);await new Promise(r=>ws.onopen=r);
let serial=0;const pending=new Map(),errors=[];ws.onmessage=e=>{const m=JSON.parse(e.data);if(m.id){const p=pending.get(m.id);pending.delete(m.id);m.error?p.reject(Error(JSON.stringify(m.error))):p.resolve(m.result)}else if(m.method==='Runtime.exceptionThrown')errors.push(m.params.exceptionDetails.text)};
const call=(method,params={})=>new Promise((resolve,reject)=>{const id=++serial;pending.set(id,{resolve,reject});ws.send(JSON.stringify({id,method,params}))});
const evaluate=async expression=>{const r=await call('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(r.exceptionDetails)throw Error(JSON.stringify(r.exceptionDetails));return r.result.value};
const check=async(expression,label)=>{if(!await evaluate(expression))throw Error(label);console.log('PASS '+label)};
await call('Runtime.enable');await call('Page.enable');await call('Emulation.setDeviceMetricsOverride',{width:1100,height:1000,deviceScaleFactor:1,mobile:false});
await call('Page.navigate',{url:'http://127.0.0.1:8766/staging-ui/equipment-icons-v1/equipment-preview.html'});
await new Promise(r=>setTimeout(r,1300));
await check(`window.previewReady&&document.querySelectorAll('.armory-card').length===18`,'inventory pages a large catalogue');
await check(`[...document.querySelectorAll('.catalogue-icon')].every(i=>i.complete&&i.naturalWidth>0)`,'generated item icons load');
await evaluate(`window.query=document.querySelector('.armory-filters input');query.focus();query.value='storm lance';query.dispatchEvent(new Event('input'))`);
await check(`document.activeElement===query&&document.querySelectorAll('.armory-card').length===1&&document.querySelector('.armory-card').textContent.includes('Stormglass')`,'skill search retains focus');
await evaluate(`document.querySelector('.armory-card [data-instance]').click()`);await new Promise(r=>setTimeout(r,150));
await check(`window.equipCalls.length===1&&document.querySelector('.armory-equipped').textContent.includes('Stormglass')`,'injured character equips immediately');
await evaluate(`document.querySelector('[data-remove="weapon"]').click()`);await new Promise(r=>setTimeout(r,150));
await check(`window.equipCalls.length===2&&window.fixture.state.characters[0].equipment.weapon===null`,'quick unequip works');
await evaluate(`let q=document.querySelector('.armory-filters input');q.value='rusty';q.dispatchEvent(new Event('input'))`);
await check(`document.querySelectorAll('.armory-card').length===1&&document.querySelector('.armory-card').textContent.includes('×2')`,'duplicate copies stack');
await evaluate(`{let q=document.querySelector('.armory-filters input');q.value='';q.dispatchEvent(new Event('input'))}`);
const shot=await call('Page.captureScreenshot',{format:'png'});writeFileSync('staging-ui/equipment-icons-v1/equipment-desktop.png',Buffer.from(shot.data,'base64'));
await call('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});await new Promise(r=>setTimeout(r,200));
await check(`document.documentElement.scrollWidth<=innerWidth`,'narrow inventory has no horizontal overflow');
if(errors.length)throw Error(errors.join('\n'));console.log('PASS no equipment script errors');ws.close();
