r"""Extract the approved uniform presentation packs; never modify source sheets.

Run from the dev checkout with .venv\Scripts\python.exe tools/import_combat_presentation.py.
Writes stable icon IDs, the runtime mapping and an extraction manifest.
"""
import json
import sys
from pathlib import Path
from PIL import Image

ROOT=Path(__file__).resolve().parents[1]
sys.path.insert(0,str(ROOT))
from backend.job_loadouts import JOBS

STAGING=ROOT/'staging-ui/combat-presentation-v2'
PUBLIC=ROOT/'frontend/public/assets/combat-presentation-v2'
GROUPS=[['fighter','barbarian','rogue','ranger'],['mage','cleric','monk','bard'],['druid','engineer','summoner','captor']]
EFFECTS=['barrier_shell','barrier_hit','barrier_break','poison_cloud','ember_ground','flame_lick','ember_motes','smoke_wisp',
         'binding_ring','binding_tether','sanctuary_ring','restoration_wisp','thorn_ground','thorn_growth','magic_hit','physical_hit']

def extract(source,names,columns,rows,folder,size):
    image=Image.open(STAGING/source)
    if abs(image.width/image.height-columns/rows)>.02:raise ValueError(f'{source}: incorrect grid aspect ratio')
    records=[]
    for index,name in enumerate(names):
        c,r=index%columns,index//columns
        box=tuple(round(v) for v in (c*image.width/columns,r*image.height/rows,(c+1)*image.width/columns,(r+1)*image.height/rows))
        tile=image.crop(box)
        if tile.getbbox() is None:raise ValueError(f'{source}: empty cell {name}')
        output=PUBLIC/folder/f'{name}.png';output.parent.mkdir(parents=True,exist_ok=True)
        tile.resize((size,size),Image.Resampling.LANCZOS).save(output,optimize=True)
        records.append({'name':name,'source':source,'cell':index,'box':box,'output':output.relative_to(ROOT).as_posix()})
    return records

def main():
    mapping={};records=[]
    for pack,jobs in enumerate(GROUPS,1):
        ids=[sid for job in jobs for sid in JOBS[job]['starter_skills']+[u['skill_id'] for u in JOBS[job]['unlocks']]]
        names=[sid.replace(':','_') for sid in ids]
        records.extend(extract(f'job-icons-{pack:02}.png',names,6,4,'icons',128))
        mapping.update({sid:f'/assets/combat-presentation-v2/icons/{name}.png' for sid,name in zip(ids,names)})
    records.extend(extract('effects-atlas.png',EFFECTS,4,4,'effects',256))
    (ROOT/'frontend/src/ability-icon-manifest.js').write_text('// Generated by tools/import_combat_presentation.py.\nexport const JOB_ICON_ART='+json.dumps(mapping,indent=2)+';\n',encoding='utf-8')
    (STAGING/'asset-manifest.json').write_text(json.dumps({'icons':mapping,'extraction':records},indent=2),encoding='utf-8')
    print(f'Imported {len(mapping)} square Job icons and {len(EFFECTS)} transparent effect components.')

if __name__=='__main__':main()
