import assert from 'node:assert/strict';
import {writeFile} from 'node:fs/promises';
const tabs=await(await fetch('http://127.0.0.1:9229/json')).json(),ws=new WebSocket(tabs.find(t=>t.type==='page').webSocketDebuggerUrl);
await new Promise(r=>ws.onopen=r);let serial=0;const pending=new Map(),errors=[];
ws.onmessage=e=>{const m=JSON.parse(e.data);if(m.id){pending.get(m.id)?.(m);pending.delete(m.id)}if(m.method==='Runtime.exceptionThrown')errors.push(m.params.exceptionDetails.exception?.description||JSON.stringify(m.params.exceptionDetails))};
const call=(method,params={})=>new Promise((resolve,reject)=>{const id=++serial;pending.set(id,m=>m.error?reject(m.error):resolve(m.result));ws.send(JSON.stringify({id,method,params}))});
const evaluate=async expression=>{const r=await call('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(r.exceptionDetails)throw Error(JSON.stringify(r.exceptionDetails));return r.result.value},wait=ms=>new Promise(r=>setTimeout(r,ms));
await call('Runtime.enable');await call('Page.enable');await call('Emulation.setDeviceMetricsOverride',{width:1440,height:1000,deviceScaleFactor:1,mobile:false});await call('Page.navigate',{url:'http://127.0.0.1:8766/staging-ui/mage-v1/preview.html'});
for(let i=0;i<180;i++){if(await evaluate('Boolean(window.mageReady)'))break;await wait(180)}
console.log('Startup errors:',errors);assert.equal(await evaluate('Boolean(window.mageReady)'),true);await wait(400);
assert.equal(await evaluate(`Array.from(document.images).filter(i=>i.src.includes('mage-v1')&&i.getClientRects().length).every(i=>i.complete&&i.naturalWidth>0)`),true);
await writeFile('staging-ui/mage-v1/elemental.png',Buffer.from((await call('Page.captureScreenshot',{format:'png'})).data,'base64'));
await evaluate(`document.querySelector('[data-hotbar-skill="job:mage:enchant_weapon"]').click();document.querySelector('.battle-token.player.current').click()`);await wait(150);
assert.equal(await evaluate(`Boolean(document.querySelector('.mage-element-prompt'))`),true);assert.equal(await evaluate('window.mageSent.length'),0);
await writeFile('staging-ui/mage-v1/enchant.png',Buffer.from((await call('Page.captureScreenshot',{format:'png'})).data,'base64'));
await evaluate(`document.querySelector('[data-mage-cancel]').click()`);assert.equal(await evaluate('window.mageSent.length'),0);
await evaluate(`document.querySelector('[data-hotbar-skill="job:mage:enchant_weapon"]').click();document.querySelector('.battle-token.player.current').click();document.querySelector('[data-mage-element="frost"]').click()`);await wait(250);
assert.equal(await evaluate('window.mageSent[0].body.element'),'frost');
await evaluate(`window.mageShow('frozen')`);await wait(650);assert.ok(await evaluate(`document.querySelectorAll('.mage-ice-shell .ice-surface').length>0`));
await writeFile('staging-ui/mage-v1/frozen.png',Buffer.from((await call('Page.captureScreenshot',{format:'png'})).data,'base64'));
for(const material of ['grass','dirt','stone']){
 await evaluate(`window.mageShow('surface_${material}')`);await wait(650);
 const counts=await evaluate(`({flames:document.querySelectorAll('.scorch-main-flame').length,minis:document.querySelectorAll('.scorch-mini-flame').length,soot:document.querySelectorAll('.scorch-soot').length,legacy:document.querySelectorAll('.mage-zone-flame').length})`);
 assert.ok(counts.soot>0&&counts.flames===counts.soot&&counts.minis===0);assert.equal(counts.legacy,0);
 const surfaceLoaded=await evaluate(`Promise.all([...new Set(Array.from(document.querySelectorAll('.battlefield svg image')).map(i=>i.getAttribute('href')).filter(h=>h?.includes('mage-scorched-v2')))].map(async url=>(await fetch(url)).ok)).then(v=>v.every(Boolean))`);assert.equal(surfaceLoaded,true);
 const geometry=await evaluate(`(()=>{const shell=document.querySelector('.mage-ice-shell'),face=shell.parentElement.querySelector('.portrait-crop'),a=shell.getBoundingClientRect(),b=face.getBoundingClientRect();return {delta:Math.abs(a.x-b.x)+Math.abs(a.y-b.y)+Math.abs(a.width-b.width),flame:document.querySelector('.scorch-flame').getBoundingClientRect().width}})()`);assert.ok(geometry.delta<1&&geometry.flame>10);
 await writeFile(`staging-ui/mage-v1/surface-${material}.png`,Buffer.from((await call('Page.captureScreenshot',{format:'png'})).data,'base64'));
}
await evaluate(`window.mageShow('fireball')`);await wait(280);assert.ok(await evaluate(`document.querySelectorAll('.mage-ice-transition').length>0`));await wait(1000);assert.equal(await evaluate(`document.querySelectorAll('.mage-ice-transition').length`),0);
await evaluate(`window.mageShow('channel')`);await wait(250);assert.ok(await evaluate(`document.querySelectorAll('.zone-meteor_armed').length>0`));
await writeFile('staging-ui/mage-v1/channel.png',Buffer.from((await call('Page.captureScreenshot',{format:'png'})).data,'base64'));
await evaluate(`window.mageShow('meteor')`);await wait(100);assert.ok(await evaluate(`Array.from(document.querySelectorAll('[data-scorch-cell]')).some(n=>n.style.visibility==='hidden')`));await wait(200);assert.ok(await evaluate(`document.querySelectorAll('.mage-effect').length>0`));
assert.equal(await evaluate(`Array.from(document.querySelectorAll('.mage-effect')).every(i=>i.complete&&i.naturalWidth>0)`),true);
await writeFile('staging-ui/mage-v1/meteor.png',Buffer.from((await call('Page.captureScreenshot',{format:'png'})).data,'base64'));await wait(1300);assert.equal(await evaluate(`document.querySelectorAll('.mage-effect').length`),0);assert.equal(await evaluate(`document.querySelectorAll('[data-scorch-cell][style*=hidden]').length`),0);
for(const name of ['chain','fireball','gravity','wind']){await evaluate(`window.mageShow('${name}')`);let visible=false;for(let i=0;i<25;i++){await wait(40);if(await evaluate(`document.querySelectorAll('.mage-effect').length>0`)){visible=true;break}}assert.ok(visible,`${name} has a visible impact`);await writeFile(`staging-ui/mage-v1/${name}.png`,Buffer.from((await call('Page.captureScreenshot',{format:'png'})).data,'base64'));await wait(2200)}
assert.deepEqual(errors,[]);console.log('Mage browser checks passed: icons, cancelled/selected enchant, ice shell, channel telegraph, all five impact effects and cleanup.');
await evaluate(`window.mageShow('elemental')`);await wait(250);
await evaluate(`document.querySelector('[data-hotbar-skill="job:mage:fireball"]').click()`);
const cursor=await evaluate(`(()=>{const token=document.querySelector('.battle-token.enemy.spell-ground-target');return token?{cursor:getComputedStyle(token).cursor,rect:{x:token.getBoundingClientRect().x+token.getBoundingClientRect().width/2,y:token.getBoundingClientRect().y+token.getBoundingClientRect().height/2}}:null})()`);
assert.ok(cursor);assert.match(cursor.cursor,/magic_cursor/);
await call('Input.dispatchMouseEvent',{type:'mouseMoved',x:cursor.rect.x,y:cursor.rect.y});
await wait(100);
const forecasts=await evaluate(`Array.from(document.querySelectorAll('.aoe-preview-chip')).map(c=>({text:c.textContent,danger:c.classList.contains('friendly-fire-forecast'),color:getComputedStyle(c.querySelector('b')).color}))`);
assert.ok(forecasts.some(f=>!f.danger));
const sent=await evaluate('window.mageSent.length');
await call('Input.dispatchMouseEvent',{type:'mousePressed',x:cursor.rect.x,y:cursor.rect.y,button:'right',buttons:2,clickCount:1});
await call('Input.dispatchMouseEvent',{type:'mouseReleased',x:cursor.rect.x,y:cursor.rect.y,button:'right',buttons:0,clickCount:1});
assert.equal(await evaluate('window.mageInspect().mode'),'move');assert.equal(await evaluate('window.mageSent.length'),sent);
await evaluate(`document.querySelector('[data-hotbar-skill="job:mage:enchant_weapon"]').click();document.querySelector('.battle-token.player.current').click()`);
assert.ok(await evaluate(`Boolean(document.querySelector('.mage-element-prompt'))`));
const prompt=await evaluate(`(()=>{const r=document.querySelector('.mage-enchant-card').getBoundingClientRect();return {x:r.x+10,y:r.y+10}})()`);
await call('Input.dispatchMouseEvent',{type:'mousePressed',...prompt,button:'right',buttons:2,clickCount:1});await call('Input.dispatchMouseEvent',{type:'mouseReleased',...prompt,button:'right',buttons:0,clickCount:1});
assert.equal(await evaluate(`Boolean(document.querySelector('.mage-element-prompt'))`),false);assert.equal(await evaluate('window.mageInspect().mode'),'move');
await evaluate(`(async()=>{const {animateStatusPlayback}=await import('/frontend/src/combat-status-playback.js');const token=document.createElement('div');token.id='qa-status-token';document.body.append(token);const unit={id:'rat',alive:true,statuses:[{id:'burn',stacks:1}]};animateStatusPlayback({units:{rat:{statuses:[]}}},{units:{rat:unit},status_definitions:{}},[{start:0,duration:700,event:{type:'mage_cast'}},{start:300,duration:900,event:{type:'combat_feedback',unit_id:'rat',statuses_snapshot:unit.statuses}}],()=>token,x=>String(x));})()`);
assert.equal(await evaluate(`Boolean(document.querySelector('#qa-status-token [data-unit-status="burn"]'))`),false);await wait(380);assert.equal(await evaluate(`Boolean(document.querySelector('#qa-status-token [data-unit-status="burn"]'))`),true);
await wait(400);await evaluate(`document.querySelector('#qa-status-token').remove()`);
await evaluate(`window.mageShow('elemental')`);await wait(250);await evaluate(`document.querySelector('[data-hotbar-skill="job:mage:fireball"]').click()`);
const selfCell=await evaluate(`(()=>{const r=document.querySelector('.battle-token.player.current').getBoundingClientRect();return {x:r.x+r.width/2,y:r.y+r.height/2}})()`);
await call('Input.dispatchMouseEvent',{type:'mouseMoved',...selfCell});await wait(80);
const friendly=await evaluate(`Array.from(document.querySelectorAll('.friendly-fire-forecast')).map(c=>({text:c.textContent,color:getComputedStyle(c.querySelector('b')).color}))`);
assert.ok(friendly.some(c=>c.text.startsWith('You')));assert.ok(friendly.every(c=>c.color==='rgb(255, 172, 164)'));
await call('Input.dispatchMouseEvent',{type:'mousePressed',...selfCell,button:'right',buttons:2,clickCount:1});await call('Input.dispatchMouseEvent',{type:'mouseMoved',x:selfCell.x+35,y:selfCell.y+15,button:'right',buttons:2});await call('Input.dispatchMouseEvent',{type:'mouseReleased',x:selfCell.x+35,y:selfCell.y+15,button:'right',buttons:0,clickCount:1});assert.equal(await evaluate('window.mageInspect().mode'),'skill');
await writeFile('staging-ui/mage-v1/friendly-forecast.png',Buffer.from((await call('Page.captureScreenshot',{format:'png'})).data,'base64'));
await evaluate(`window.mageShow('navigation')`);await wait(200);await evaluate(`document.querySelector('[data-combat-mode="move"]').click()`);
const hazardCell=await evaluate(`(()=>{const r=document.querySelector('[data-battle-cell="2,3"]').getBoundingClientRect();return {x:r.x+r.width/2,y:r.y+r.height/2}})()`);
await call('Input.dispatchMouseEvent',{type:'mouseMoved',...hazardCell});await wait(180);
const hazard=await evaluate(`(()=>{const c=document.querySelector('.movement-hazard-card');return {visible:!c.hidden,text:c.textContent,marked:document.querySelectorAll('.hazard-path-preview').length}})()`);
assert.equal(hazard.visible,true);assert.match(hazard.text,/2 HP damage/);assert.match(hazard.text,/Bleed.*hurts at turn end/);assert.equal(hazard.marked,1);
await evaluate(`(()=>{const prop=document.createElement('div');prop.className='battle-terrain';document.querySelector('.battlefield').append(prop)})()`);
const cursors=await evaluate(`({open:getComputedStyle(document.querySelector('.battle-door-control.is-closed')).cursor,close:getComputedStyle(document.querySelector('.battle-door-control.is-open')).cursor,prop:getComputedStyle(document.querySelector('.battle-terrain')).cursor,blocked:getComputedStyle(document.querySelector('.battle-cell:not(.reachable)')).cursor})`);
assert.match(cursors.open,/door_open_cursor/);assert.match(cursors.close,/door_close_cursor/);assert.match(cursors.prop,/pointer_cursor/);assert.match(cursors.blocked,/unavailable_cursor/);
assert.ok(await evaluate(`document.querySelectorAll('.exit-marker img[src*="retreat.png"]').length>0`));
await writeFile('staging-ui/mage-v1/navigation.png',Buffer.from((await call('Page.captureScreenshot',{format:'png'})).data,'base64'));
console.log('PASS route hazard card, delayed Bleed wording, highlighted hazardous cells, painted doors/props/blocked cursors and retreat markers.');
await evaluate(`window.mageShow('boss_freeze_ready')`);await wait(100);
await evaluate(`window.mageShow('boss_freeze_expired')`);await wait(320);
assert.equal(await evaluate(`window.mageInspect().blocked`),true);
assert.equal(await evaluate(`Array.from(document.querySelectorAll('.battle-token.enemy .mage-ice-transition')).some(e=>e.style.backgroundImage.includes('freeze_'))`),true);
await writeFile('staging-ui/mage-v1/boss-freeze.png',Buffer.from((await call('Page.captureScreenshot',{format:'png'})).data,'base64'));
await wait(520);
assert.equal(await evaluate(`Array.from(document.querySelectorAll('.battle-token.enemy .mage-ice-transition')).some(e=>e.style.backgroundImage.includes('thaw_'))`),true);
await wait(680);
assert.equal(await evaluate(`document.querySelectorAll('.battle-token.enemy .mage-ice-transition').length`),0);
assert.equal(await evaluate(`Array.from(document.querySelectorAll('.battle-token.enemy .mage-ice-shell')).every(e=>e.style.visibility==='hidden')`),true);
assert.equal(await evaluate(`window.mageInspect().blocked`),false);
console.log('PASS solo Mage boss freeze -> portrait ice -> thaw within one response, without a lingering shell or early input unlock.');
assert.equal(errors.length,0,errors.join('\n'));console.log('PASS occupied AoE magic cursor, right-click Move/cost-free cancel including enchant prompt, timed Burn badges.');ws.close();
