import assert from 'node:assert/strict';
const tabs=await(await fetch('http://127.0.0.1:9229/json')).json();
const ws=new WebSocket(tabs.find(t=>t.type==='page').webSocketDebuggerUrl);await new Promise(r=>ws.onopen=r);
let serial=0;const pending=new Map(),errors=[];
ws.onmessage=e=>{const m=JSON.parse(e.data);if(m.id){const p=pending.get(m.id);pending.delete(m.id);m.error?p.reject(Error(JSON.stringify(m.error))):p.resolve(m.result)}else if(m.method==='Runtime.exceptionThrown')errors.push(m.params.exceptionDetails.text)};
const call=(method,params={})=>new Promise((resolve,reject)=>{const id=++serial;pending.set(id,{resolve,reject});ws.send(JSON.stringify({id,method,params}))});
const evaluate=async expression=>{const r=await call('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(r.exceptionDetails)throw Error(JSON.stringify(r.exceptionDetails));return r.result.value};
await call('Runtime.enable');await call('Page.enable');
await call('Emulation.setFocusEmulationEnabled',{enabled:true});
await call('Page.navigate',{url:'http://127.0.0.1:8766/staging-ui/combat-relationships/preview.html'});
for(let i=0;i<100;i++){if(await evaluate('Boolean(window.relationshipReady)'))break;await new Promise(r=>setTimeout(r,100))}
for(const [width,height] of [[1440,1000],[1280,720],[800,700]]){
 await call('Emulation.setDeviceMetricsOverride',{width,height,deviceScaleFactor:1,mobile:false});await evaluate("window.nativePreview();document.querySelector('[data-battle-fit]').click()");await new Promise(r=>setTimeout(r,150));
 const dimensions=await evaluate(`(()=>{const v=document.querySelector('#battle-viewport'),f=v.querySelector('.battlefield'),r=f.getBoundingClientRect(),b=v.getBoundingClientRect();return {width:r.width,height:r.height,availableWidth:v.clientWidth,availableHeight:v.clientHeight,bottom:b.bottom,screen:innerHeight}})()`);
 assert.ok(dimensions.width<=dimensions.availableWidth+1,JSON.stringify(dimensions));assert.ok(dimensions.height<=dimensions.availableHeight+1,JSON.stringify(dimensions));assert.ok(dimensions.bottom<=height,JSON.stringify(dimensions));
 console.log('fit map',width,height,dimensions);
 const camera=await evaluate("(()=>{const buttons=[...document.querySelectorAll('.battle-camera button')].map(b=>b.getBoundingClientRect());return {tops:buttons.map(b=>b.top),widths:buttons.map(b=>b.width)}})()");
 assert.ok(Math.max(...camera.tops)-Math.min(...camera.tops)<1,'Camera controls share one row');
 assert.ok(Math.max(...camera.widths)-Math.min(...camera.widths)<1,'Camera buttons share equal widths');
 const zoomed=await evaluate("(()=>{document.querySelector('[data-battle-zoom=in]').click();return document.querySelector('.battlefield').getBoundingClientRect().width})()");
 assert.ok(zoomed>dimensions.width,'Zoom in must enlarge the fitted map');
 await evaluate("document.querySelector('[data-battle-fit]').click()");
 const wheel=await evaluate(`(()=>{const v=document.querySelector('#battle-viewport'),f=v.querySelector('.battlefield'),before=f.getBoundingClientRect().width,r=v.getBoundingClientRect();v.dispatchEvent(new WheelEvent('wheel',{deltaY:-10,clientX:r.left+r.width/2,clientY:r.top+r.height/2,bubbles:true,cancelable:true}));return {before,after:f.getBoundingClientRect().width,same:f===v.querySelector('.battlefield')}})()`);
 assert.ok(wheel.after>wheel.before&&wheel.after<wheel.before*1.05);assert.equal(wheel.same,true);
 const modified=await evaluate("(()=>{const v=document.querySelector('#battle-viewport'),f=v.querySelector('.battlefield'),before=f.getBoundingClientRect().width;v.dispatchEvent(new WheelEvent('wheel',{deltaY:-10,shiftKey:true,bubbles:true,cancelable:true}));return {before,after:f.getBoundingClientRect().width}})()");assert.equal(modified.before,modified.after);
}
await call('Emulation.setDeviceMetricsOverride',{width:1440,height:1000,deviceScaleFactor:1,mobile:false});
await new Promise(r=>setTimeout(r,150));
await evaluate('window.relationshipPreview()');
assert.equal(await evaluate("document.querySelector('[data-roster-panel=conversation] .character-record-grid')===null"),true);
await evaluate("document.querySelector('[data-roster-tab=record]').click()");assert.equal(await evaluate("!document.querySelector('[data-roster-panel=record]').classList.contains('hidden')"),true);
await evaluate("document.querySelector('[data-roster-tab=overview]').click();document.querySelector('[data-stat-help]').focus()");
const tooltip=await evaluate("(()=>{const p=document.querySelector('.floating-help'),r=p.getBoundingClientRect();return {hidden:p.hidden,text:p.textContent,left:r.left,right:r.right,bottom:r.bottom}})()");
assert.equal(tooltip.hidden,false);assert.match(tooltip.text,/Effective attribute/);assert.ok(tooltip.left>=0&&tooltip.right<=1440&&tooltip.bottom<=1000);
await evaluate("localStorage.removeItem('fortcamp:hide-equipped:fixture-guild:fixture-user:details');window.qolEquipment()");
assert.equal(await evaluate("[...document.querySelectorAll('.armory-effects')].every(d=>d.open)"),true);
assert.match(await evaluate("document.querySelector('.armory-equipped-details').textContent"),/Meridian|Grants|Uses/);
assert.equal(await evaluate("document.querySelector('.armory-equipped-details').tagName"),'DIV');
await evaluate("document.querySelector('[data-hide-details]').click();document.querySelector('[data-roster-tab=overview]').click();document.querySelector('[data-roster-tab=equipment]').click()");
assert.equal(await evaluate("[...document.querySelectorAll('.armory-effects')].every(d=>!d.open)"),true);
assert.ok(await evaluate("document.querySelector('.armory-equipped-details').getBoundingClientRect().height>0"),'Equipped effects remain visible when spare details are hidden');
await evaluate("window.qolContract()");assert.equal(await evaluate("document.querySelector('#mission-modal').classList.contains('hidden')"),false);
await evaluate("document.querySelector('.reservation-heading').click()");assert.equal(await evaluate("document.querySelector('#mission-modal').classList.contains('hidden')"),false);
await evaluate("document.querySelector('#mission-modal').click()");assert.equal(await evaluate("document.querySelector('#mission-modal').classList.contains('hidden')"),true);
await evaluate('window.qolVictory()');
const banner=await evaluate("(()=>{const a=document.querySelector('.battle-victory-overlay .victory-decision').getBoundingClientRect(),b=document.querySelector('#battle-viewport').getBoundingClientRect();return {dx:Math.abs((a.left+a.right-b.left-b.right)/2),dy:Math.abs((a.top+a.bottom-b.top-b.bottom)/2),width:a.width,height:a.height,mapHeight:b.height}})()");
assert.ok(banner.dx<2&&banner.dy<2,JSON.stringify(banner));assert.ok(banner.width>banner.height);
await evaluate("document.querySelector('[data-combat-action=continue_pursuit]').click()");await new Promise(r=>setTimeout(r,150));
assert.equal(await evaluate("document.querySelector('.battle-victory-overlay')===null&&Boolean(document.querySelector('[data-victory-expand]'))"),true);
await evaluate("document.querySelector('[data-victory-expand]').click()");assert.equal(await evaluate("Boolean(document.querySelector('.battle-victory-overlay'))"),true);
await evaluate("document.querySelector('[data-victory-minimize]').click()");assert.equal(await evaluate("document.querySelector('.battle-victory-overlay')===null"),true);
await evaluate('window.prisonPreview()');
await evaluate("document.querySelector('[data-prison-talk]').open=true;document.querySelector('[data-prisoner-action=talk]').click()");await new Promise(r=>setTimeout(r,150));
assert.match(await evaluate("document.querySelector('.prison-talk-reply').textContent"),/timber/);
assert.equal(await evaluate("document.querySelector('[data-prisoner-action=recruit]').disabled"),true);
await evaluate("window.confirm=()=>true;document.querySelector('[data-prisoner-action=fulfill]').click()");await new Promise(r=>setTimeout(r,150));
assert.equal(await evaluate("document.querySelector('[data-prisoner-action=recruit]').disabled"),false);
await evaluate("document.querySelector('[data-prisoner-action=recruit]').click()");await new Promise(r=>setTimeout(r,150));
assert.equal(await evaluate("document.querySelector('[data-prison-talk]')===null"),true);
assert.deepEqual(errors,[]);console.log('Camera, equipment, victory and prisoner talk/payment/recruitment checks passed.');
await call('Browser.close');ws.close();
