// Isolated Summoner UI regression fixture; no live API or player saves.
import assert from 'node:assert/strict';
import {writeFile} from 'node:fs/promises';
const tabs=await(await fetch('http://127.0.0.1:9229/json')).json();
const ws=new WebSocket(tabs.find(t=>t.type==='page').webSocketDebuggerUrl);
await new Promise(r=>ws.onopen=r);let serial=0;const pending=new Map(),errors=[];
ws.onmessage=e=>{const m=JSON.parse(e.data);if(m.id){pending.get(m.id)?.(m);pending.delete(m.id)}if(m.method==='Runtime.exceptionThrown')errors.push(m.params.exceptionDetails.exception?.description)};
const call=(method,params={})=>new Promise((resolve,reject)=>{const id=++serial;pending.set(id,m=>m.error?reject(m.error):resolve(m.result));ws.send(JSON.stringify({id,method,params}))});
const evaluate=async expression=>{const r=await call('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(r.exceptionDetails)throw Error(JSON.stringify(r.exceptionDetails));return r.result.value};
const wait=ms=>new Promise(r=>setTimeout(r,ms));
await call('Runtime.enable');await call('Page.enable');await call('Network.enable');await call('Network.setCacheDisabled',{cacheDisabled:true});await call('Emulation.setDeviceMetricsOverride',{width:1440,height:1000,deviceScaleFactor:1,mobile:false});
await call('Page.navigate',{url:'http://127.0.0.1:8766/staging-ui/mage-v1/preview.html'});
for(let i=0;i<120;i++){if(await evaluate('Boolean(window.mageReady)'))break;await wait(200)}
assert.equal(await evaluate('Boolean(window.mageReady)'),true);


await evaluate(`window.mageShow('summoner_ready')`);await wait(500);
assert.equal(await evaluate(`document.querySelectorAll('[data-hotbar-skill]').length`),6);
assert.equal(await evaluate(`document.querySelector('[data-hotbar-skill="innate:summoner:orders"]').getAttribute('aria-disabled')`),'true');
await evaluate(`document.querySelector('[data-hotbar-skill="job:summoner:bound_companion"]').click()`);
assert.match(await evaluate(`document.querySelector('.summoner-panel').textContent`),/Choose a companion/);
assert.equal(await evaluate(`document.querySelector('[data-summon-confirm]').disabled`),true);
await evaluate(`document.querySelector('[data-summon-element="earth"]').click()`);
await evaluate(`document.querySelector('[data-battle-cell="0,0"]').click()`);
assert.equal(await evaluate(`document.querySelector('[data-summon-confirm]').disabled`),false);
assert.equal(await evaluate(`window.mageSent.length`),0);
await writeFile('staging-ui/summoner-v1/companion-placement.png',Buffer.from((await call('Page.captureScreenshot',{format:'png'})).data,'base64'));
await evaluate(`document.body.dispatchEvent(new KeyboardEvent('keydown',{key:'e',bubbles:true}))`);await wait(250);
assert.equal(await evaluate(`window.mageSent.at(-1).body.element`),'earth');
assert.deepEqual(await evaluate(`window.mageSent.at(-1).body.positions`),[{x:0,y:0}]);
await evaluate(`window.mageShow('summoner_ready')`);await wait(100);
await evaluate(`document.querySelector('[data-hotbar-skill="job:summoner:wisp_swarm"]').click()`);
for(const p of ['0,0','1,0','2,0'])await evaluate(`document.querySelector('[data-battle-cell="${p}"]').click()`);
assert.equal(await evaluate(`document.querySelector('[data-summon-confirm]').disabled`),false);
await evaluate(`document.querySelector('[data-summon-confirm]').click()`);await wait(200);
assert.equal(await evaluate(`window.mageSent.at(-1).body.positions.length`),3);
await evaluate(`window.mageShow('summoner_active')`);await wait(500);
assert.equal(await evaluate(`document.querySelectorAll('[data-battle-unit^="entity_"]').length`),4);
assert.equal(await evaluate(`Array.from(document.querySelectorAll('[data-battle-unit^="entity_"] img')).filter(i=>i.src.includes('summoner-v1')).every(i=>i.naturalWidth>0)`),true);
await evaluate(`document.querySelector('[data-hotbar-skill="innate:summoner:orders"]').click()`);
await evaluate(`document.querySelector('[data-summon-order="stand_down"]').click()`);
await writeFile('staging-ui/summoner-v1/group-orders.png',Buffer.from((await call('Page.captureScreenshot',{format:'png'})).data,'base64'));
await evaluate(`document.querySelector('[data-summon-confirm]').click()`);await wait(250);
assert.deepEqual(await evaluate(`window.mageSent.at(-1).body`),{action:'summon_order',entity_id:'all',order:'stand_down'});
await evaluate(`window.mageShow('summoner_active')`);await wait(150);
await evaluate(`document.querySelector('[data-hotbar-skill="innate:summoner:orders"]').click()`);
assert.equal(await evaluate(`document.querySelector('[data-summon-order="follow"]').textContent`),'Follow Summoner');
await evaluate(`document.querySelector('[data-summon-order="protect"]').click()`);
assert.equal(await evaluate(`document.querySelector('[data-summon-confirm]').disabled`),true);
await evaluate(`document.querySelector('.battle-token.enemy').click()`);
assert.equal(await evaluate(`document.querySelector('[data-summon-confirm]').disabled`),true);
const protectedOwner=await evaluate(`window.mageInspect().actor.id`);
await evaluate(`(()=>{const select=document.querySelector("[data-summon-protect-target]");select.value="${protectedOwner}";select.dispatchEvent(new Event("change",{bubbles:true}));})()`);
assert.equal(await evaluate(`document.querySelector('[data-summon-confirm]').disabled`),false);
assert.match(await evaluate(`document.querySelector('.summoner-panel').textContent`),/without intercepting attacks/);
await writeFile('staging-ui/summoner-v1/protect-summoner.png',Buffer.from((await call('Page.captureScreenshot',{format:'png'})).data,'base64'));
await evaluate(`document.querySelector('[data-summon-confirm]').click()`);await wait(150);
assert.deepEqual(await evaluate(`window.mageSent.at(-1).body`),{action:'summon_order',entity_id:'all',order:'protect',target_id:protectedOwner});
await evaluate(`window.mageShow('summoner_active')`);await wait(150);
await evaluate(`document.querySelector('[data-hotbar-skill="innate:summoner:orders"]').click()`);
await evaluate(`const select=document.querySelector('[data-summon-group]');select.value='entity_2_0';select.dispatchEvent(new Event('change',{bubbles:true}))`);
assert.equal(await evaluate(`document.querySelector('[data-summon-order="protect"]')`),null);
await evaluate(`document.querySelector('[data-summon-cancel]').click()`);
await evaluate(`window.mageShow('summoner_active')`);await wait(150);
await evaluate(`document.querySelector('[data-hotbar-skill="job:summoner:bound_companion"]').click()`);
assert.match(await evaluate(`document.querySelector('.summoner-panel h3').textContent`),/Reclaim/);
await evaluate(`document.querySelector('[data-summon-cancel]').click()`);
assert.equal(await evaluate(`document.querySelector('.summoner-panel:not([hidden])')`),null);
await evaluate(`window.mageShow('summoner_payoff')`);await wait(200);
await evaluate(`document.querySelector('[data-hotbar-skill="job:summoner:transposition"]').click()`);
const owner=await evaluate(`window.mageInspect().actor.id`);
await evaluate(`document.querySelector('[data-battle-unit="${owner}"]').click()`);
await evaluate(`document.querySelector('[data-battle-unit="entity_1_0"]').click()`);
assert.equal(await evaluate(`document.querySelector('[data-summon-confirm]').disabled`),false);
await evaluate(`document.querySelector('[data-summon-confirm]').click()`);await wait(250);
assert.equal(await evaluate(`window.mageSent.at(-1).body.ally_id`),owner);
await evaluate(`window.mageShow('summoner_payoff')`);await wait(200);
await evaluate(`document.querySelector('[data-hotbar-skill="job:summoner:spirit_projection"]').click()`);
await evaluate(`document.querySelector('.battle-token.enemy').click()`);
assert.match(await evaluate(`document.querySelector('.summoner-panel').textContent`),/4 contributions/);
await writeFile('staging-ui/summoner-v1/projection-preview.png',Buffer.from((await call('Page.captureScreenshot',{format:'png'})).data,'base64'));
await evaluate(`document.querySelector('[data-summon-cancel]').click()`);
await evaluate(`document.querySelector('[data-hotbar-skill="job:summoner:sacrifice"]').click()`);
await evaluate(`document.querySelector('[data-battle-cell="5,2"]').click()`);
assert.match(await evaluate(`document.querySelector('.summoner-panel').textContent`),/damaging and blinding nearby allies/);
assert.equal(await evaluate(`document.querySelectorAll('.summoner-target-layer .danger').length`),9);
assert.equal(await evaluate(`document.querySelector('[data-summon-confirm]').disabled`),false);
await evaluate(`document.dispatchEvent(new KeyboardEvent('keydown',{key:'c',bubbles:true}))`);
assert.equal(await evaluate(`document.querySelector('.summoner-panel:not([hidden])')`),null);
await evaluate(`document.querySelector('[data-hotbar-skill="innate:summoner:orders"]').click()`);
await evaluate(`document.querySelector('.summoner-panel').dispatchEvent(new MouseEvent('contextmenu',{bubbles:true,cancelable:true}))`);
assert.equal(await evaluate(`document.querySelector('.summoner-panel:not([hidden])')`),null);
assert.equal(await evaluate(`window.mageInspect().mode`),'move');
await evaluate(`window.mageShow('summoner_sacrifice')`);await wait(200);
assert.equal(await evaluate(`document.querySelectorAll('.summoner-effect img').length>0`),true);
await writeFile('staging-ui/summoner-v1/sacrifice-playback.png',Buffer.from((await call('Page.captureScreenshot',{format:'png'})).data,'base64'));
await wait(2000);
assert.equal(await evaluate(`document.querySelectorAll('.summoner-effect').length`),0);
await evaluate(`window.mageShow('summoner_overload')`);await wait(700);
assert.equal(await evaluate(`document.querySelectorAll('.summoner-overload-aura').length`),1);
await writeFile('staging-ui/summoner-v1/overload-aura.png',Buffer.from((await call('Page.captureScreenshot',{format:'png'})).data,'base64'));
await evaluate(`window.mageShow('summoner_death_before')`);await wait(200);
const death=await evaluate(`window.mageEventTimes('summoner_death_after').find(r=>r.skill==='summoner_dissolve'&&r.unit_id==='entity_2_0')`);
assert.ok(death.start>1000);
await evaluate(`window.mageShow('summoner_death_after')`);await wait(200);
assert.equal(await evaluate(`document.querySelector('[data-battle-unit="transition-entity_2_0"]')?.isConnected`),true);
assert.equal(await evaluate(`Number(getComputedStyle(document.querySelector('[data-battle-unit="transition-entity_2_0"]')).opacity)>.9`),true);
await writeFile('staging-ui/summoner-v1/pending-summon-death.png',Buffer.from((await call('Page.captureScreenshot',{format:'png'})).data,'base64'));
await wait(death.start+death.duration+200);
assert.equal(await evaluate(`document.querySelector('[data-battle-unit="transition-entity_2_0"]')`),null);
assert.equal(await evaluate(`document.querySelector('[data-battle-unit="entity_2_0"]')`),null);
assert.equal(await evaluate(`document.querySelectorAll('.battle-field-toolbar [data-summon-orders]').length`),0);
await evaluate(`window.mageShow('summoner_ready')`);await wait(100);
await evaluate(`window.mageShow('summoner_birth_death')`);await wait(800);
assert.equal(await evaluate(`document.querySelector('[data-battle-unit="transition-entity_2_0"]')?.isConnected`),true);
assert.equal(await evaluate(`Number(getComputedStyle(document.querySelector('[data-battle-unit="transition-entity_2_0"]')).opacity)>.9`),true);
await wait(3500);
assert.equal(await evaluate(`document.querySelector('[data-battle-unit="transition-entity_2_0"]')`),null);
assert.deepEqual(errors,[]);console.log('PASS Summoner placement, portraits, group commands, Reclaim, Transposition, Projection, Sacrifice preview/playback and keyboard/right-click cancellation.');ws.close();
